wjakob/nanobind

- include/nanobind/nb_error.h
- include/nanobind/nb_tuple.h
- src/error.cpp
- tests/test_classes.cpp
I did some brief static analysis with clang-tidy and found some code improvements (a reason I suggested adding basic clang-tidy checks). Mainly it adds noexcepts which can make certain STL constructs able to use their move constructors. It also removed a useless std::move in the move constructor for src/error.cp since the base class std::exception apparently does not have a move constructor.
> Apply noexcept to appropiate std::move constructors

- setup.py
When I use `#include <nanobind/stl/vector.h>`, I currently get
```
/private/var/folders/k8/fypg6j5x187dmhbw3q_047s40000gp/T/pip-build-env-8kz_3qma/overlay/lib/python3.9/site-packages/nanobind/include/nanobind/stl/vector.h:3:10: fatal error: 'detail/nb_list.h' file not found
#include "detail/nb_list.h"
```
I'm assuming this would fix it.
> Include detail/nb_list.h in the package

- include/nanobind/nb_accessor.h
- include/nanobind/nb_lib.h
- src/buffer.h
- src/nb_func.cpp
This PR adds in a couple of fixes up:
1. Simplifies a few new line string literals into chars.
2. Moves default initialization out of the constructors if they are always the same.
> Apply more minor clang-tidy fixes

- include/nanobind/nb_attr.h
- include/nanobind/nb_class.h
- src/nb_type.cpp
- tests/test_classes.cpp
- tests/test_classes.py
This PR adds dynamic attribute access (analogous to pybind11's
``nb::dynamic_attr()`` flag) while using only ``Py_LIMITED_API``
functionality.
> Dynamic attribute access

- include/nanobind/nb_lib.h
- include/nanobind/nb_types.h
- src/common.cpp
Hi!
Small PR, just added support for assigning non-null names to capsules.
This is helpful for a bunch of things, eg:
- Taking advantage of `scipy.LowLevelCallable` (name needs to be set to a function signature)
- Creating "custom call" targets for XLA/JAX (name needs to be set to `xla._CUSTOM_CALL_TARGET`)
> Support named capsules

- include/nanobind/nb_lib.h
- include/nanobind/nb_types.h
- src/common.cpp
- tests/test_functions.cpp
- tests/test_functions.py
Added support for using the `bytes` type as an input or output to bound functions. This would be super helpful for me!
> Support Python byte strings

- src/nb_type.cpp
- tests/test_classes.cpp
- tests/test_classes.py
The return value policy specifications in pybind11 and nanobind involve a troublesome corner case: the policy is ignored if an object with the specified reference already exists, since ownership is then unproblematic.
This can lead to to the puzzling situation, in which `v1` and `v2` in the below Python script refer to the same object.
```cpp
// C++ bindings
nb::class<Struct>(m, "Struct")
.def("get1", [](Struct &s){ return s.data; }, rv_policy::reference_internal)
.def("get2", [](Struct &s){ return s.data; });
```
```python
s = Struct()
v1 = s.get1()
v2 = s.get2()
```
One would ordinarily expect that the bindings of the `get2()` lambda function (which returns a reference) will create a copy based on the default (`rv_policy::automatic`) return value policy. But the returned reference is …
> Guarantee a copy is made with rv_policy::copy

- src/tensor.cpp
- tests/test_tensor.cpp
- tests/test_tensor.py
I found the following tensor creation for a 0-dim array ([array scalars in numpy](https://numpy.org/doc/stable/reference/arrays.scalars.html)) causes SIGSEGV.
This PR adds checking of array dimension to fix it and accept the creation. Could you please merge this?
```c++
nb::class_<Dummy>(module, "NanobindTest")
.def(nb::init<>())
.def(
"ret_array_scalar", [](const Dummy&) {
float* f = new float[1]{1};
size_t shape[0] = {};
nb::capsule deleter(f,
[](void* data) noexcept
{
delete[](float*) data;
});
return nb::tensor<nb::numpy, float>(f, 0, shape, deleter);
});
```
> Fix tensor creation for zero-dimensional arrays

- cmake/nanobind-config.cmake
- include/nanobind/stl/string_view.h
- tests/test_stl.cpp
- tests/test_stl.py
A small update to automatically type cast `std::string_view`.
> Add type caster for string_view.

- cmake/nanobind-config.cmake
- include/nanobind/nanobind.h
- include/nanobind/nb_func.h
- include/nanobind/nb_traits.h
- include/nanobind/stl/optional.h
- include/nanobind/stl/variant.h
- tests/test_stl.cpp
- tests/test_stl.py
The `std::optional` and `std::variant` casters are implemented. This makes it easy to handle overloading of some types that contain `None` as an argument or return value, and also simplifies function signatures. I would be grateful if this would be accepted.
```cpp
m.def("optional_copyable", [](std::optional<Copyable> &) {}, nb::arg("x").none());
m.def("optional_unbound_type", [](std::optional<int> &x) { return x; }, nb::arg("x").none() = nb::none());
```
```python
t.optional_copyable(t.Copyable())
t.optional_copyable(None)
t.optional_unbound_type(3)
t.optional_unbound_type(None)
t.optional_unbound_type()
```
In particular, if the argument of a non-bound type such as `nb::list` or `int` can take `None`, the `std::optional` caster can simplify overloading and function signatures.
Note …
> std::optional and std::variant casters

- CMakeLists.txt
Summary:
* Avoid re-finding python if its CMake target already exists.  This is useful when the client's cmake already have python setup and re-finding python may result in error.
> Minor CMake Update

- include/nanobind/stl/detail/nb_dict.h
- include/nanobind/stl/map.h
- include/nanobind/stl/unordered_map.h
- tests/test_stl.cpp
- tests/test_stl.py
I've implemented a `std::map` and `std::unordered_map` type caster that converts to/from a Python `dict`. I've extracted the common logic into `detail/nb_dict.h` similar to the current implementation for `std::list` and `std::vector` in `detail/nb_list.h`.
> Add std::map and std::unordered_map type casters

- include/nanobind/stl/detail/nb_dict.h
- tests/test_stl.cpp
- tests/test_stl.py
The dictionary caster that I wrote has a compilation issue when the `std::map` is passed into the C++ caster as a `const &`. This change fixes it. I would also note that the same issue should probably be fixed in #84 as the conversion logic was modified from the dictionary caster.
```
nanobind/include/nanobind/stl/detail/nb_dict.h:57:43: error: type 'const std::map<std::__cxx11::basic_string<char>, std::vector<unsigned long, std::allocator<unsigned long>>, std::less<std::__cxx11::basic_string<char>>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::vector<unsigned long, std::allocator<unsigned long>>>>> &' cannot be used prior to '::' because it has no members
forward_like<typename T::key_type>(item.first), policy, cleanup));
^
```
> Fix dict type caster compilation with `const &`

- include/nanobind/tensor.h
When mapping the data (e.g. via Eigen::Map) a cast is needed to convert the output of data() to the correct type. Since this is always deterministic I think the return type of data should be changed.
> Change return type of tensor::data() to Scalar, use consistent spelling

- include/nanobind/nb_defs.h
- include/nanobind/stl/detail/nb_set.h
- include/nanobind/stl/unordered_set.h
- tests/test_stl.cpp
- tests/test_stl.py
This PR adds type castor for `std::unordered_set`, and is part of #84, which is split into two parts. Here we don't do the same for `std::set` since Python doesn't have an ordered set by default.
> add support to unordered_set

- include/nanobind/nb_types.h
- tests/test_functions.cpp
- tests/test_functions.py
This PR adds support for the `slice` and `ellipsis` types. It would be useful for binding array-like classes. 
As a side note, the name `EllipsisType` is based on the [`typing.EllipsisType`](https://docs.python.org/dev/library/types.html#types.EllipsisType) introduced in Python 3.10.
> Add nb::slice and nb::ellipsis types

- include/nanobind/nb_class.h
- tests/test_classes.cpp
- tests/test_classes.py
- tests/test_stl.cpp
- tests/test_stl.py
This commit implements a simple optimization that applies when the following two conditions hold:
- A field in a bound C++ types is exposed as writeable Python property
- Setting the field involves an inter-language type conversion step (e.g., for `type_caster<std::vector<T>>` implemented in ``nanobind/stl/vector.h``)
In this case, we can avoid a superfluous copying step by move-constructing the constructed instance from the type caster directly into the field.
This commit also adds tests to verify that this actually happens under the hood.
> Exploit move constructors in def_readwrite and def_readwrite_static

- include/nanobind/stl/function.h
- src/nb_internals.cpp
- tests/test_functions.py
- tests/test_stl.cpp
- tests/test_stl.py
This commit adds:
- Roundtrip support! When a Python function has been wrapped in a ``std::function<>``, subsequent conversion to a Python object will return the original Python function object.
Note that this is the opposite of pybind11's ``std::function<>`` caster, where roundtrip support is implemented for C function pointers (which isn't possible in nanobind currently, and seems less useful in retrospect).
- Building on the previous point, the following C++ snippet
```cpp
nb::object o = nb::cast(std_function_instance, nb::rv_policy::none); 
```
can be used to attempt a conversion of a ``std::function<>`` instance into a Python object. This will either return the function object or an invalid (``!o.is_valid()``) object if the conversion fails.
What is the point of these changes? A …
> Major improvements to the std::function<> caster (roundtrips, cyclic GC)

- include/nanobind/nb_defs.h
- include/nanobind/nb_types.h
- include/nanobind/stl/detail/nb_dict.h
- include/nanobind/stl/detail/nb_set.h
- include/nanobind/stl/pair.h
- include/nanobind/stl/tuple.h
- tests/test_classes.py
- tests/test_functions.py
- tests/test_stl.py
This is a very minor change: this PR unifies the type names of collection types appearing in STL casters, depending on the Python version.  
According to the [PEP 585](https://peps.python.org/pep-0585/), Python 3.9 or later allows built-in collection types to be used for type annotations.
> PEP 585 generics in type names

- tests/object.cpp
This file uses `fprintf`, and it should include what it uses.
> Add missing cstdio header from tests/object.cpp.

- include/nanobind/nb_types.h
If `NB_OBJECT` is used from a different namespace outside nanobind, the `detail::` relative namespace cannot be resolved.
> Fully qualify detail:: namespace used in NB_OBJECT macro.

- src/nb_type.cpp
In a heap-allocated type, tp_members normally points to the interior of the type object, at offset tp_basicsize. By copying the tp_members field of a temporary heap-allocated type object to the final type object, we leave a dangling pointer. Instead, allocate space for the PyMemberDef objects at the end of the nanobind-allocated type object, copy them into place, and set tp_members to point to that location.
> Fix dangling tp_members pointer.

- README.md
- include/nanobind/nb_lib.h
- include/nanobind/nb_misc.h
- src/common.cpp
- src/nb_internals.cpp
- src/nb_internals.h
The reasoning behind this is as follows:
In our project, we again ran into a reference-counting issue, which isn't caused by our own extension library, but most likely caused by the PyTorch extension library, see here: https://github.com/tingyu66/nanobind_example/commit/8629419b6ffa4416d4f3e5cb99f9a6731359cb32
We don't have the bandwidth/time to investigate all these issues in other libraries, and in general, we have no control over what other extension libraries our end users run the library with.
In order to avoid bothering users with leak reports, this PR adds a mechanism to suppress leak reports which would be used for builds distributed to end users.
Of course by default, we keep the leak reports on, in order to catch these during development, as well as in our own CI.
> Add compile-time variable to suppress leak warnings

- include/nanobind/nb_enums.h
- include/nanobind/stl/detail/nb_dict.h
- include/nanobind/stl/detail/nb_list.h
- include/nanobind/stl/detail/nb_set.h
- include/nanobind/stl/list.h
Fixes wrong paths/file names in some of nanobind's include copyright headers.
> Fix file name typos in include copyright headers

- include/nanobind/nb_class.h
- include/nanobind/stl/bind_map.h
- include/nanobind/stl/detail/traits.h
- tests/CMakeLists.txt
- tests/test_stl_bind_map.cpp
- tests/test_stl_bind_map.py
Adds a port of pybind11's `bind_map` to nanobind, including tests.
For now, all additions have been made inline in the new header file, nanobind/stl/bind_map.h. This file opts the user into the standard library headers `<string>` (due to its use of string concatenation for constructing dynamic keys/values view names) and `<memory>` (for dynamically allocating keys/values/items views.)
--------------------------------------------------------------------------
This is my best effort of porting over `py::bind_map`, so far. Since I am not writing C++ that often, please be relentless so that I can learn and do better :)
The use of `<string>` and `<memory>` are only necessary because I ported over https://github.com/pybind/pybind11/pull/4353, which pulls them in for dynamically constructing …
> Add `nb::bind_map`

- src/nb_internals.cpp
- src/nb_type.cpp
nanobind fails to compile on Visual Studio 2017 and GCC 7.3.1 (the compiler version in the Red Hat Developer Toolset for RHEL 7) because it uses C++20 designated initializers for the `PyType_Spec` structs in nb_type.cpp and nb_internals.cpp. Replacing these with aggregate initializers allows nanobind to compile on these older compilers.
Refer to discussion in https://github.com/wjakob/nanobind/discussions/108
> Switch from C++20 designated initializers to aggregate initializers to support older compilers

- .github/workflows/ci.yml
- docs/changelog.rst
- docs/removed.md
- include/nanobind/eigen.h
- include/nanobind/nb_lib.h
- include/nanobind/nb_traits.h
- include/nanobind/nb_types.h
- include/nanobind/tensor.h
- src/nb_internals.cpp
- src/nb_internals.h
- src/tensor.cpp
- tests/CMakeLists.txt
- tests/test_eigen.cpp
- tests/test_eigen.py
This commit adds custom casters for the Eigen linear algebra library. It uses the existing `nb_tensor` infrastructure to implement a conversion between Eigen types and NumPy arrays that currently supports:
- `Eigen::Matrix/Array<..>` and derived types (row/column vectors)
- `Eigen::Map<..>`
- `Eigen::Ref<..>`
- Expression templates (`CwiseBinaryOp`, etc.)
There are a few limitations:
- Eigen tensors are not supported yet.
- Sparse matrix types are not supported yet.
> Initial support for the Eigen library

- .github/workflows/ci.yml
- docs/changelog.rst
- docs/eigen.rst
- docs/index.rst
- include/nanobind/eigen/dense.h
- include/nanobind/eigen/sparse.h
- tests/CMakeLists.txt
- tests/test_eigen.cpp
- tests/test_eigen.py
This is a first attempt at supporting sparse matrix types from Eigen. The code is mostly ported over from [pybind11](https://github.com/pybind/pybind11/blob/master/include/pybind11/eigen/matrix.h). It compiles but the test segfaults. This could have to with the fact that I have not really a good idea of what I'm doing. Help is very much appreciated.
> eigen: support sparse matrix types

- cmake/nanobind-config.cmake
- docs/exchanging.rst
- include/nanobind/stl/filesystem.h
- tests/test_stl.cpp
- tests/test_stl.py
Summary:
* Add type caster for `std::filesystem::path` ~~or `std::experimental::filesystem::path`~~ to `pathlib.Path` based on [pybind11's counterpart](https://github.com/pybind/pybind11/blob/master/include/pybind11/stl/filesystem.h).
* Add unit test and update doc.
> Add filesystem support

- include/nanobind/nanobind.h
nanobind uses types from <exception> without including the header, e.g., std::exception. This will break in future versions of libc++, where not all such types are available via transitive includes.
> Add <exception> to headers included by nanobind.

- include/nanobind/ndarray.h
- src/nb_ndarray.cpp
- tests/test_ndarray.cpp
- tests/test_ndarray.py
This pull request adds support for bool ndarray. The bool type was introduced in DLPack [v0.8](https://github.com/dmlc/dlpack/issues/75).
The changes are ad follows:
* Add bool type to dtype code
* Add tests for NumPy, TensorFlow, and JAX.
*  [PyTorch](https://github.com/pytorch/pytorch/blob/0c7ca2d97ba5980a2af7dcd6b8106dc915e591cd/aten/src/ATen/dlpack.h#L89) does not seem to support the bool type yet (?)
@wjakob Could you review this?
> Support bool ndarray

- src/nb_func.cpp
- src/nb_internals.cpp
- tests/test_classes.cpp
- tests/test_classes.py
A subtle side effect of how
``nb_func``/``nb_method``/``nb_bound_method`` attribute getters were implemented caused problems in combination with IPython (see issue #148). This commit explores an alternative approach.
> Implement nb_func.__{name,qualname,module}__ without properties

- include/nanobind/stl/optional.h
- include/nanobind/stl/pair.h
The std::pair type_caster is missing an `bool IsClass = false;`.
Without that an error is triggered when building and using `def_rw` together with an std::pair.
The problem is not covered by the tests.
> Add missing IsClass to std::pair type_caster

- docs/why.rst
The word 'is' was repeated in "Why another binding library?".
> Pedantic fix : '... is is ...' -> '... is ...'

- docs/api_extra.rst
- include/nanobind/ndarray.h
- tests/test_ndarray.cpp
- tests/test_ndarray.py
Fixes https://github.com/wjakob/nanobind/discussions/158
I was not sure how you deal with tests. I could not find tests for e.g. `stride` to I tried to be non-intrusive. But let me know if you want otherwise.
> NumPy: adding `size`, `shape_ptr`, `stride_ptr`

- include/nanobind/nb_defs.h
This is similar to what pybind11 does:
https://github.com/pybind/pybind11/blob/4ce05175d51a4685232452bdc1e9cbb13a240a65/include/pybind11/detail/common.h#LL372-L374
Pasting the macro argument directly does not work, as demonstrated by: https://godbolt.org/z/Kv9EEfEsY
> Wrap `PyInit_##name` in macro to allow macros as module names

- include/nanobind/nb_attr.h
Add missing 1 since `rv_policy` spans 3 bits. One effect of this bug is that supplying a return value policy to properties does not work properly.
> Fix func_extra_apply for rv_policy

- src/nb_func.cpp
Remove '<anonymous>' from docstring.  It's left in the error message for convenience.
Related to https://github.com/wjakob/nanobind/discussions/171 .
> Remove '<anonymous>' from docstring

- src/nb_ndarray.cpp
- tests/test_ndarray.cpp
- tests/test_ndarray.py
Sorry for making a pullrequest instead of an issue, but it looks like pytorch does not always set the stride of its outermost dimension equal to 0 or the "expected stride" (i.e., the stride you would get if you increased the singleton dimension to a length greater than 1) when that dimension is singleton (i.e., that dimension's length is 1). Instead, it uses a stride of 1. `ndarray_import` assumes that singleton dimensions either have the "expected stride" or 0. If this isn't the case, you get an error about "incompatible function arguments".
I wrote a few reproducers for this issue, as well as a basic fix, though I admit it's a bit "ugly". However, since the only index that will ever be valid for a dimension of size 1 is 0, its stride will never be used anyway.
Edit: Upon further …
> Fix for ndarray_import when tensor imported is batch size 1.

- include/nanobind/nb_types.h
An `explicit operator bool()` can still be used in conditional tests without a cast (`if (h) { ... }`) and is a better match for the explicitness of, for example, `operator int()` in `nb::int_`. Without this change, if you write
```
void fn(nb::int_ ival) {
int i = ival;
printf("%d\n", i);
}
```
then `fn(nb::int_(42))` will print 1. (Only implicit conversions are allowed by the initialization style used, so the implicit `operator bool` in `nb::handle` is eligible while the explicit `operator int` in `nb::int_` is not.)
> nb::handle: make bool conversion explicit to avoid ambiguity with integer conversions in derived types

- docs/api_core.rst
- include/nanobind/nb_cast.h
The uses are analogous to those in argument position; for example, you might want to return `nb::iterator` but indicate in the signature that it's an iterator over some specific type. It almost worked already, just had a typo in the `type_caster`.
> nb::typed<>: support use in return position

- docs/benchmark.rst
- docs/changelog.rst
- include/nanobind/nb_class.h
- include/nanobind/nb_lib.h
- src/nb_internals.cpp
- src/nb_type.cpp
Split fields that are only needed during type object initialization (doc, base, base_py, type_slots) into a new `type_init_data` structure, so that the persistent `type_data` doesn't need to store them.//
Split off from #192
> Refactor type_data to save space

- docs/api_core.rst
- docs/changelog.rst
- docs/lowlevel.rst
- docs/typeslots.rst
- include/nanobind/nb_attr.h
- include/nanobind/nb_class.h
- include/nanobind/nb_lib.h
- src/nb_enum.cpp
- src/nb_internals.h
- src/nb_type.cpp
- tests/test_enum.cpp
- tests/test_enum.py
Remove all enum-specific logic from `type_data` and `nb_type.cpp`; instead, `nb::enum_` now implements all of its additional functionality through the same interface available to user code (using `type_slots` and `supplement`). This serves as a demonstration of how nanobind users can implement their own enum-like semantics, and frees up four flag bits for other uses.
Cache the enum's scope, `is_signed` flag, and entries dictionary in supplemental type data. Caching the scope allows it to move out of `type_data` (enums were the only entity using it after type initialization was complete). Caching the entries dictionary makes enum lookups by value (used in `__new__`, `__name__`, and `__repr__`) substantially faster.
On my laptop, `python3.9 -m timeit -s "from test_enum_ext import Enum"` …
> Reduce nb_type/nb_enum entanglement

- include/nanobind/nb_func.h
- tests/test_functions.cpp
- tests/test_functions.py
Currently, binding a function that takes an rvalue reference (let's say `std::ranges::find`) only works if you don't pass a call guard. Otherwise it fails with `error: cannot bind rvalue reference of type ‘[$type]&&’ to lvalue of type ‘[$type]’`. Forwarding the arguments should fix this issue.
> Forward the arguments inside call_guard wrapper lambda

- docs/api_core.rst
- docs/changelog.rst
- src/nb_enum.cpp
- tests/test_enum.py
* Enum equality comparisons (``==`` and ``!=``) now can only be true if both operands have the same enum type, or if one is an enum and the other is an `int`. This resolves some confusing results and ensures that enumerators of different types have a distinct identity, which is important if they're being put into the same set or used as keys in the same dictionary. All of the following were previously true but will now evaluate as false:
* ``FooEnum(1) == BarEnum(1)``
* ``FooEnum(1) == 1.2``
* ``FooEnum(1) == "1"``
* Enum ordering comparisons (``<``, ``<=``, ``>=``, ``>``) and arithmetic operations (when using the :cpp:struct:`is_arithmetic` annotation) now require that any non-enum operand be a Python number (an object that defines ``__int__``, ``__float__``, and/or ``__index__``) and …
> Fix surprising behavior in enum comparisons and arithmetic

- docs/changelog.rst
- docs/ownership.rst
- docs/ownership_adv.rst
- docs/porting.rst
- include/nanobind/nb_class.h
- include/nanobind/nb_traits.h
- include/nanobind/stl/shared_ptr.h
- src/nb_type.cpp
- tests/test_holders.cpp
- tests/test_holders.py
Per discussion in https://github.com/wjakob/nanobind/discussions/183, this is not actually dangerous, although it does have some caveats (which I think I've thoroughly documented).
This turned out better than I thought it would: it is unexpectedly possible to support the feature where returning a raw pointer whose `enable_shared_from_this` subobject knows about a shared_ptr creates a Python object that shares ownership with that shared_ptr, without requiring `#include <memory>` anywhere in nanobind that doesn't already have it.
Size impact: `nb_type.cpp.o` increases by 148 bytes. Use of `std::shared_ptr<T>` in non-`enable_shared_from_this` cases actually gets smaller; we were previously instantiating a deleter for `PyObject*` by mistake, and now we're not.
> Support enable_shared_from_this

- docs/changelog.rst
- src/nb_func.cpp
- src/nb_internals.cpp
- tests/test_classes.py
The introspection attributes `__self__` and `__func__` provide better interface compatibility with regular Python bound methods, and can be cheaply supported by adding new entries in the existing member list.
The previous wholesale forwarding of attribute accesses to the underlying `nb_func` produced surprising behavior when explicitly invoking dunder methods: `obj.method()` would work but `obj.method.__call__()` would not (it would need `obj.method.__call__(obj)`). Same thing for `__repr__`, `__hash__`, etc. Fix this by checking the 'normal' attribute path before delegating to the contained method, except for `__doc__` and `__module__` where we want `nb_func`'s version even though the attribute does exist in `nb_bound_method`'s class dict as well. This is necessary to support `__self__` …
> nb_bound_method: add introspection attributes and fix surprising behavior around wrapper descriptors

- .github/workflows/ci.yml
- cmake/darwin-ld-cpython.sym
- docs/changelog.rst
- docs/typeslots.rst
- src/common.cpp
- src/nb_static_property.cpp
- src/nb_type.cpp
- tests/test_functions.cpp
*This commit currently fails because the CI still builds against Python 3.12a7 that doesn't yet have PEP697. It will be merged once the GHA setup-python action has caught up with 3.12 beta*
PEP 697 introduced a new limited C API to extend opaque types. nanobind needs this feature because it stashes internal type data structures within Python ``type`` objects. Previously, we assumed a standard Python memory layout for such opaque types and did not do anything special besides adding an offset to get to the nanobind part.
However, such an approach is not acceptable when using nanobind to compile future-proof stable ABI wheels: the Python team may at some point significantly refactor the layout and internals of ``type`` objects, which would lead to undefined behavior in combination with our …
> Use PEP-697 interface to access stashed data in type objects

- docs/api_extra.rst
- docs/changelog.rst
- docs/ndarray.rst
- include/nanobind/nb_lib.h
- include/nanobind/ndarray.h
- src/nb_ndarray.cpp
- tests/test_ndarray.cpp
- tests/test_ndarray.py
This PR adapts nanobind so that it can both receive and return arrays representing read-only memory. This is communicated via the standard ``const`` type modifier, e.g. by replacing ``nb::ndarray<float, ...>`` with ``nb::ndarray<const float, ...>``.
The PR also adapts accessors (``data()``, ``operator()``) so that they only return constant references/pointers in that case.
The change is for now specific to the buffer protocol used to exchange nd-arrays with NumPy. The DLPack interface (used to exchange nd-arrays with PyTorch, Tensorflow, etc.) ignores the read-only annotation. This may change at some point in the future when an upcoming DLPack version with a read-only bit is more widely deployed.
This PR only targets the ``ndarray`` class. It will be nice to also propagate it into the …
> Read-only array exchange via the buffer protocol

- CMakeLists.txt
- cmake/nanobind-config.cmake
This commit fixes the naming conventions of ABI3 builds on Windows. It also adopts a recent CMake/FindPython interface whenever available.
> Fix naming of ABI3 extension libraries on Windows

- docs/changelog.rst
- docs/lowlevel.rst
- include/nanobind/nb_class.h
- include/nanobind/trampoline.h
- src/nb_func.cpp
- src/nb_internals.cpp
- src/nb_internals.h
- src/nb_type.cpp
- src/trampoline.cpp
- tests/test_classes.py
- tests/test_stl_bind_map.py
- tests/test_stl_bind_vector.py
This commit simplifies and optimizes the performance-critical function dispatch loop (both simple + complex variants).
This previously did a few extra things that are now all moved to other places:
- Ensuring that an already initialized class cannot be initialized again (the class type caster now checks for this)
- Ensuring sure that ``super().function()`` within a trampoline reaches the parent class implementation of ``function()``, which required tracking some TLS state. This functionality is now moved to the trampolines.
- Double-checking that the 'self' type in a constructor is actually a class bound via nanobind. This is now checked when the binding is first created.
> Function dispatcher optimization

- cmake/nanobind-config.cmake
This should speed up the configuration by sometimes reducing the calls to Python of CMake is new enough. 
Testing in https://github.com/wjakob/nanobind_example/pull/27, but the cross compile situation requires further work.
> fix: use FindPython's suffix computation if possible

- src/nb_enum.cpp
- src/nb_internals.h
- src/nb_type.cpp
This PR splits the overly complicated function `inst_new` into two alternative code paths `inst_new_ext` and `inst_new_int`.
> inst_new simplifications

- include/nanobind/ndarray.h
This PR fixes the construction of a read-only bool ndarray that is incorrectly treated as a uint type.
> Fix bool type detection for read-only ndarray construction

- cmake/nanobind-config.cmake
- docs/api_cmake.rst
This fixes a small bug in the cmake function `nanobind_compile_options`, where the `name` parameter was missing.
I also noticed a small error in the documentation of `nanobind_add_module`, not sure if this should go into a separate pull request.
> Add missing cmake parameter

- include/nanobind/nb_attr.h
- include/nanobind/nb_func.h
- src/nb_func.cpp
Thanks for your library!
Using nanobind release 1.5.0, I faced the following compilation error with MSVC 2022 in DEBUG mode (`_DEBUG` defined) only due to macro `free` being defined as `_free_dbg` by Windows headers:
```
nb_func.cpp(94,20): error C2039: '_free_dbg': is not a member of 'nanobind::detail::func_data'
```
I am aware you wish to keep the project easily maintainable and this is a quick and least intrusive fix, however I am not yet familiar with nanobind so not sure it is the most ideal or correct approach.
Anyway here it is just in case :)
> fix MSVC compilation error in DEBUG mode due to free macro

- docs/classes.rst
Eliminates the small typo `share_ptr ` ->  `shared_ptr`.
> Fix `std::shared_ptr` code example in documentation

- include/nanobind/stl/complex.h
- tests/test_stl.cpp
- tests/test_stl.py
This is an attempt to add support for complex numbers using a `type_caster` (previously discussed as #286 ).
With test code:
```
#include <nanobind/nanobind.h>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/complex.h>
namespace nb = nanobind;
#include <iostream>
typedef double value_t;
// typedef float value_t;
std::complex<value_t> foo(const std::complex<value_t>& x){
std::cout << "x=" << x << " sizeof(complex value)=" << 8*sizeof(x) << "b" << std::endl;
return x;
}
std::vector<std::complex<value_t>> foo_array(const std::vector<std::complex<value_t>>& x){
std::cout << "x[0]=" << x[0] << " sizeof(complex element)=" << 8*sizeof(x[0]) << "b" << std::endl;
std::cout << "x[1]=" << x[1] << " sizeof(complex element)=" << 8*sizeof(x[1]) << "b" << std::endl;
return x;
}
NB_MODULE(pybar, …
```
> Add type caster for complex numbers

- include/nanobind/stl/variant.h
- tests/test_stl.cpp
- tests/test_stl.py
This PR fixes the missing `None` check in the `std::variant` caster. 
The following code produces SIGABRT at runtime since the change in 1220156961ce2d0c96a525f3c27b88e824b997ce;
```c++
m.def("variant_copyable_none", [](std::variant<int, Copyable, std::monostate> &) {}, nb::arg("x").none());
```
```python
t.variant_copyable_none(None)
```
This PR include
* Improve test coverage
* Revert the `None` check
* Refactoring of redundant code
> Fix None check in variant caster

- include/nanobind/eigen/dense.h
- tests/test_eigen.cpp
- tests/test_eigen.py
There is a flaw in type_caster<Eigen::Map<T>>: instead of testing T's constness, it tests the constness of Map itself, which can never be const. 
The writability of numpy.ndarray's returned for Eigen::Map is not tested yet, and so I have added respective tests.
> Made type_caster<Eigen::Map<T>> correctly consider T's constness

- docs/ndarray.rst
- include/nanobind/ndarray.h
- include/nanobind/stl/complex.h
- src/nb_ndarray.cpp
- tests/test_ndarray.cpp
- tests/test_ndarray.py
This PR introduces support for complex numbers in the `ndarray` type.
- Added a trait `is_complex_t` to identify complex number types.
- Updated `ndarray_traits` to include an `is_complex` trait.
- Modified `is_ndarray_scalar_v` to account for complex numbers.
- Introduced a new `ndarray_arg` specialization for complex numbers.
- Updated the dtype function to handle complex numbers and return the appropriate dtype code.
- Extended the format switch-case in `nd_ndarray_tpbuffer` to handle complex numbers with 64 and 128 bits.
> Complex numbers support for ndarray.

- tests/test_ndarray.cpp
- tests/test_ndarray.py
Following #https://github.com/wjakob/nanobind/pull/338#issuecomment-1779217448, tests added that fail with read-only complex Numpy array.
See #342.
> Add failing Numpy read-only test to test suite

- include/nanobind/stl/optional.h
- tests/test_stl.cpp
- tests/test_stl.py
Currently if any code uses `std::nullopt`, it will throw a `bast_cast` exception as no type_caster has been defined for it: https://github.com/wjakob/nanobind/discussions/274. 
As `std::nullopt` is a standard way to assign empty value to `std::optional`, so I think it is better to add the type_caster for it in `stl/optional.h`
> Add type_caster for `std::nullopt`

- include/nanobind/eigen/dense.h
- tests/test_eigen.cpp
- tests/test_eigen.py
As discussed in issue https://github.com/wjakob/nanobind/issues/330, Eigen::Ref was missing the `from_cpp()` method in it's type caster. I essentially copied the from_cpp() method from the Eigen::Map type caster.
> added from_cpp() method for the Eigen::Ref type_caster

- src/nb_internals.h
Switch from `std::hash<string>` to `std::hash<string_view>` to avoid creating new std::string (which could involve memory allocation and copy) when doing hash for type name.
> For hashing type name, using `std::hash<std::string_view>` instead of `std::hash<std::string>` 

- CMakeLists.txt
- cmake/nanobind-config.cmake
Package ecosystems that know how to install CMake projects can now package nanobind for distribution without using submodule'd dependencies.
nanobind does not install any compiled library artifacts. Instead, all necessary source files and supporting CMake files are installed to build nanobind within another CMake project.
A CMake user can now adjust the CMake option `NB_USE_SUBMODULE_DEPS` to choose whether nanobind will use and/or install the submodule'd external dependencies. This is `ON` by default, allowing nanobind's CMake logic to continue operating as it did previously.
Another CMake option was introduced, `NB_CREATE_INSTALL_RULES`, to allow users to choose whether to enable or disable the installation rules. Notably, if nanobind is added to a CMake project with `add_subdirectory`, …
> cmake: Add install rules and option to use submodule dependencies

- CMakeLists.txt
For packagers, these changes fix an issue caused by the `find_package(Python)` call that cannot be avoided without patching. This call places a requirement on Python during CMake configuration, even though it's not a requirement for building and installing nanobind. While this point is subtle, it's ideal to install/package nanobind without requiring unnecessary external dependencies.
> Minimize required CMake dependencies when only installing

- include/nanobind/intrusive/ref.h
`type_caster<ref>::from_cpp` missed an optimization so far: if no copy shall be made and `intrusive_base::self_py` returns a valid pointer, then return it directly and spare the time to lookup the instance map.
> type_caster<ref>::from_cpp: use ref->self_py

- include/nanobind/nb_lib.h
- include/nanobind/nb_types.h
- src/common.cpp
Ported over from the corresponding pybind11 implementation
> Add support for bool

- cmake/nanobind-config.cmake
nanobind adds `/bigobj and /MP` as compiler options for MSVC which results in this issue previously seen in pybind11.
https://github.com/pybind/pybind11/issues/3883
The same fix has been ported over in this PR.
> Fix incompatible MSVC options being passed through to nvcc

- docs/changelog.rst
- include/nanobind/nb_cast.h
- tests/test_classes.cpp
- tests/test_classes.py
Previously it could raise an exception from the `type_caster`'s conversion operator, which would then crash the program due to `try_cast` being `noexcept`.
> Avoid a crash in nb::try_cast<T>(nb::none())

- docs/basics.rst
- docs/ownership.rst
- docs/typeslots.rst
Found a few typos when reading through the documentation.
The custom type slots example was also wrong/flipped.
> Fix minor typos in documentation

- include/nanobind/eigen/sparse.h
- tests/test_eigen.cpp
Without fully qualifying `nanobind::make_tuple` the new test raises the following compiler error.
```c++
In file included from /home/henri/Code/nanobind/tests/test_eigen.cpp:3:
/home/henri/Code/nanobind/include/nanobind/eigen/sparse.h: In instantiation of ‘static nanobind::handle nanobind::detail::type_caster<T, typename std::enable_if<is_eigen_sparse_matrix_v<T>, int>::type>::from_cpp(const T&, nanobind::rv_policy, nanobind::detail::cleanup_list*) [with T = Eigen::SparseMatrix<std::complex<double> >]’:
/home/henri/Code/nanobind/include/nanobind/eigen/sparse.h:99:24:   required from ‘static nanobind::handle nanobind::detail::type_caster<T, typename std::enable_if<is_eigen_sparse_matrix_v<T>, int>::type>::from_cpp(T&&, nanobind::rv_policy, nanobind::detail::cleanup_list*) [with T = …
```
> Eigen: fix overloaded call to make_tuple is ambiguous

- include/nanobind/intrusive/counter.h
- include/nanobind/intrusive/ref.h
This PR introduces the following changes:
* Reference count changes on `intrusive_base` should be considered `const` operations
* Allow implicit casts from `ref<T>` to `T*` and `const T*`
* C-style casts on any use of `inc_ref` and `dec_ref`  to avoid type-checking.
> Changes to the `intrusive_base` and `ref<T>` interfaces

- src/nb_func.cpp
It is better to use `repr()` instead of `print()` for the string representation of the default value in the signature.
Example:
```cpp
#include <nanobind/stl/chrono.h>
module.def(
"func",
[](std::chrono::seconds time) {
...
},
"time"_a = std::chrono::seconds{10});
```
The signature
```python
func(time: datetime.timedelta = 0:00:10)
```
will be
```python
func(time: datetime.timedelta = datetime.timedelta(seconds=10))
```
> Fix string representation of default value

- cmake/nanobind-config.cmake
Refer to https://github.com/wjakob/nanobind/issues/420#issuecomment-1971548152
> Fix ARG_MARKER_FILE typo in nanobind-config.cmake

- include/nanobind/nb_defs.h
Whe compiling on ~~cygwin~~ mingw64 using gcc, errors like this occur:
```
nb_error.h:30:17: error: 'dllexport' implies default visibility, but 'class nanobind::python_error' has already been declared with a different visibility
30 | class NB_EXPORT python_error : public std::exception {
|                 ^~~~~~~~~~~~
```
This PR should fix this, with formatting changes in nearby code.
I made reference with https://gcc.gnu.org/wiki/Visibility
> Fix incorrect visibility when compiling on MinGW64 with gcc

- include/nanobind/stl/variant.h
This PR fixes ' None' is still redundant when the `Optional` is in `std::variant`.
The argument of `std::variant<T, std::optional<U>>` should be typed as `T | U | None`, but it is `T | U | None | None `. This is my old mistake about `remove_opt_mono`.
> Fix nested redundant `None` in `variant`

- include/nanobind/nb_class.h
Noticed this when upgrading our internal version. Looks like the comment accidentally got split.
> Remove misplaced comment

- include/nanobind/make_iterator.h
- tests/test_make_iterator.cpp
- tests/test_make_iterator.py
- tests/test_make_iterator_ext.pyi.ref
These can show up in certain map-like containers where the keys are stored implicitly. For example, you can imagine a map where the keys are relatively dense iterators, which chooses to store the values in a contiguous array/vector and have the key for each value be implied by its index in that vector. Dereferencing an iterator for such a map returns `pair<Key, Value&>` rather than `pair<const Key, Value>&`. Previously, nanobind's `make_key_iterator` and `make_value_iterator` functions would try to form a reference to a temporary (complete with compiler warning) if you passed them an iterator like that; after this change, they work correctly.
I verified that the unit test added here fails if I run it without the change to make_iterator.h that's being made here.
> make_key/value_iterator: support iterators that return a non-reference from operator*

- docs/classes.rst
- include/nanobind/nb_class.h
- tests/test_classes.cpp
- tests/test_classes.py
- tests/test_classes_ext.pyi.ref
This almost works already, except that `is_base_of` never returns true for unions, even when testing whether something is a base of itself. Add an `is_same` alternative, and a test to make sure this doesn't regress.
> Support binding unions

- src/nb_type.cpp
- tests/test_classes.py
I found it surprising that class with dynamic attributes (i.e., it must have a `__dict__` internally) didn't have a `o.__dict__` visible to Python users. It seems that simply setting `tp_dictoffset` isn't enough for `o.__dict__` to be present.
If the user didn't provide a `tp_getset`, populate it with `__dict__` for classes with dynamic attributes.
> Add a `__dict__` attribute to nanobind::dynamic_attr() classes.

- docs/api_extra.rst
- include/nanobind/nb_lib.h
- src/nb_ndarray.cpp
- tests/test_ndarray.py
This PR changes `ndarray_check` such that it returns `True` if one of the following conditions is met:
* The given object has a `__dlpack__` attribute
* The given object supports the CPython buffer interface
* The given object is an object from NumPy (implicit through buffer protocol), PyTorch, XLA, TensorFlow
With this change, `ndarray_check` more closely matches the logic of supported imports through `ndarray_import`.
I've added a straightforward test which checks this new behavior on an object with a `__dlpack__` attribute.
> Allow `ndarray_check` on objects of arbitrary modules

- src/nb_func.cpp
- tests/test_functions.cpp
Noticed this while reading through nb_func.cpp. I verified that the new test fails if run without the new `Py_CLEAR`.
> Fix reference leak when adding a new function overload

- include/nanobind/nb_traits.h
- include/nanobind/stl/detail/nb_array.h
- include/nanobind/stl/detail/nb_dict.h
- include/nanobind/stl/detail/nb_list.h
- include/nanobind/stl/detail/nb_set.h
- include/nanobind/stl/optional.h
- include/nanobind/stl/pair.h
- include/nanobind/stl/tuple.h
When nanobind user code enables C++23, I found that `nanobind::detail::forward_like` has a naming conflict with  `std::forward_like` in STL due to ADL.
The situation is like [this](https://godbolt.org/z/98xP78v7o):
```c++
#include <utility>
namespace nanobind {
template <typename T, typename U>
auto forward_like(U&& t) { return t; }
template <typename T>
auto func(T&& t) { return forward_like<T>(t); }
}
int main() {
auto p = std::pair(0, 0);
nanobind::func(p);
return 0;
}
```
```
x86-64 clang 17.0.1
x86-64 clang 17.0.1
-std=c++23 -stdlib=libc++ -Wall -Wextra 
123
<Compilation failed>
x86-64 clang 17.0.1 - cached
<source>:8:31: error: call to 'forward_like' is ambiguous
8 |     auto func(T&& t) { return forward_like<T>(t); }
|                               ^~~~~~~~~~~~~~~
```
In …
> Rename `forward_like` to avoid conflict with STL

- docs/ndarray.rst
- include/nanobind/nb_traits.h
- include/nanobind/ndarray.h
- include/nanobind/stl/complex.h
- tests/test_ndarray.cpp
- tests/test_ndarray.py
As an extension developer using complex numbers and having custom bindings, I do not want to use a type caster for std::complex.  However, I do want to use nb::ndarray for arrays of std::complex.
This PR adds `is_complex_v<T>` to nb_traits.h so that it is not necessary to include nanobind/stl/complex.h in order to use nb::ndarray with complex numbers.  Note that the standard library `<complex>` is **not** included so that those not using complex numbers do not pay the cost of its inclusion.
> Decouple complex ndarray from stl/complex.h.

- docs/api_extra.rst
- src/nb_ndarray.cpp
- tests/test_ndarray.cpp
- tests/test_ndarray.py
In the numpy buffer protocol, strides are measured in bytes.  If a stride (in any dimension) is not an integer multiple of itemsize, then the stride cannot be correctly converted to number of elements.
With this PR, a function taking such an nb::ndarray argument will raise a TypeError exception.
> ndarray import from buffer protocol requires integer stride.

- src/stubgen.py
Use qualified name when writing type aliases.
If you have some bindings like this:
```c++
nb::class_<A> a(m, "A");
nb::enum_<E> e(a, "E");
nb::class_<B> b(m, "B");
b.attr("E") = a.attr("E");
```
you currently get:
```python
class A:
class E(_Enum):
...
class B:
E: TypeAlias = E  
```
with this fix you get:
```python
class B:
E: TypeAlias = A.E
```
> use qualified name when aliasing types

- docs/basics.rst
The cmake outputs for the built extensions go under build\Debug so the run instructions are not the same as on other OSs.  In addition, python is just `python.exe` on Windows, not `python3`.
for #517
> add a note about running on Windows

- docs/api_core.rst
Match the order of `implicitly_convertible()` `Source` and `Target` template parameters in the example code.
Here's a screenshot of the docs for context:
> Swap target/source in implicitly_convertible example code

- tests/CMakeLists.txt
Putting outputs in Release/ folders etc is a result of using a multi-config cmake generator like Visual Studio, not of using MSVC. This fixes using ninja on windows, and presumably using multi config generators with compilers other than MSVC.
> Fix building tests with Ninja on Windows

- include/nanobind/nb_defs.h
- revert change from https://github.com/wjakob/nanobind/pull/440
- `dllexport` was/is correct on Windows, including with mingw64 gcc compiler
- don't set `visibility("hidden")` attribute for namespaces on windows
- this resolves the original mingw64 compilation error seen in #440
> Fix visibility for GCC on Windows (mingw64)

- include/nanobind/stl/wstring.h
In some cases, wchar_t strings are preferable to UTF-8 strings for non-ascii string.
So add support for std::wstring following std::string using provided Python API.
> add support for std::wstring following std::string

- include/nanobind/stl/unique_ptr.h
- tests/test_holders.cpp
- tests/test_holders.py
Support passing None where a `unique_ptr<T>` is needed (subject to argument nullability rules), and producing None when a null `unique_ptr<T>` is returned to Python.
Previously from-python conversion would pass a None object to `nb_type_relinquish_ownership` which would try to reinterpret it as a nanobind instance. Similarly, in from-cpp conversion, `nb_type_put_unique` would call `nb_type_put_unique_finalize` which would try to modify some bits in `Py_None`.
> Fix support for None in unique_ptr caster

- src/nb_func.cpp
- src/nb_internals.h
- src/nb_type.cpp
- tests/test_holders.py
Instances become relinquished when the object they wrap has its ownership transferred to a C++ `unique_ptr`. Unlike ready instances, they can't be validly accessed (because the C++ object might have been destroyed without our knowledge). Unlike non-ready instances, they can't be validly constructed (because the C++ object might still be within its lifetime). They need a new state. This PR handles them by expanding the previous `nb_inst::ready` flag into a two-bit field `nb_inst::state`. Due to a careful choice of which number represents which state, this should have negligible overhead.
Fixes #550.
> Model relinquished instances as a separate state from not-ready

- src/nb_func.cpp
The current code is C++ undefined behavior if kwargs_in is nullptr.
> Protect a reference to kwargs_in->ob_name with a nullptr test.

- src/nb_enum.cpp
The ->name field of the typeinfo is never freed at the moment.
> Don't leak enum names.

- docs/api_extra.rst
- docs/ndarray.rst
- include/nanobind/ndarray.h
- src/nb_ndarray.cpp
- tests/test_ndarray.py
Hi, this PR adds cupy support.
What additional tests do you recommend adding?
Do you think it would make sense for `np.ndarray` with `nb::device::cuda` be considered `cp.ndarray` automatically?
Reference: #510
> Add cupy support

- src/nb_func.cpp
- tests/test_issue.cpp
Currently, binding a copy constructor with a named argument corrupts the stack due to writing past the end of a stack-allocated array.
> fix named copy ctor argument

- docs/changelog.rst
- include/nanobind/nb_cast.h
Follow up to discussion #605.
I confirmed with my downstream project that the patch does indeed fix the regression introduced in nanobind 2.0.
Please note that, even though the commit has my name and email address, the actual patch was provided by @oremanj.
> Add exception to assert introduced in #549 when the type caster of `U*` can produce the actual underlying object `U`

- cmake/nanobind-config.cmake
The path of Python executable should be converted to cmake-style path to avoid invalid escape sequence.
Otherwise, `NB_STUBGEN_CMD` may contain string like `D:\mambaforge\python.exe` on Windows and will make this line writes incorrect string:
https://github.com/wjakob/nanobind/blob/c5ae2a36a704c1c62da99a81fad919261a3e9848/cmake/nanobind-config.cmake#L446
> Use cmake-style path in nanobind_add_stub

- include/nanobind/nb_class.h
- include/nanobind/nb_types.h
I read the comment about "ritual purification" in nb_attr.h, but couldn't resist.
(I don't plan more such PRs)
> remove two semicolons (-Wextra-semi ritual purification)

- docs/api_cmake.rst
I was trying to use the PATTERN_FILE mechanism to rewrite the type's inferred for c++ `Eigen::` from `numpy.typing.ArrayLike` (which is overly broad) to `numpy.typing.NDArray`.  
While [testing to see if that mechanism](https://github.com/wjakob/nanobind/discussions/630) could work for what I need -- I noticed this documentation bug.
It seems the PATTERN_FILE mechanism won't work for what I need -- but thought I'd file this doc fix anyway.
> Fix doc typo in `nanobind_add_stubgen`

- include/nanobind/eigen/dense.h
Merge requests to Eigen have just been casting to int to fix the warning.
> Fix deprecated enum-enum conversion warnings in C++20

- src/nb_internals.cpp
Populating the internals `inst_c2p` map handles the case where there are C++ instance pointer key collisions. This can occur for example when there are several distinct Python objects which reference the same memory address, such as a struct and its first member. In this instance the value within the map becomes a linked-list of type `nb_inst_seq*`.
In the case where there are reported nanobind leaks, there was missing logic to handle the possibility of the values in our `inst_c2p` map being a linked-list and hence this PR adds this additional check.
> Handle print leaks when `inst_c2p` has collisions

- src/nb_ndarray.cpp
there is a 80 bytes leak everytime a bytes is implicitely converted into ndarray
```=================================================================
==190==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 80 byte(s) in 1 object(s) allocated from:
#0 0x7fd4e29e961f in malloc (/lib64/libasan.so.8+0xdd61f) (BuildId: 1d5b30c36844ba264ef3e2de667e7a3b01c75e84)
#1 0x7fd4e2300848 in PyMem_Malloc (/lib64/libpython3.11.so.1.0+0x1dd848) (BuildId: 1c275add58b260eaed423bcf6f89cf5b753a0389)
#2 0x7fd4e06b2117  (/mnt/docker/.venv/lib64/python3.11/site-packages/mre.cpython-311-x86_64-linux-gnu.so+0x53117) (BuildId: 453c323ff2f76c062da0865a220d35eb8a5b7614)
#3 0x7fd4e06b4430  (/mnt/docker/.venv/lib64/python3.11/site-packages/mre.cpython-311-x86_64-linux-gnu.so+0x55430) (BuildId: …
```
> fix memory leak when implicitely converting bytes into ndarray

- src/stubgen.py
- tests/py_stub_test.py
- tests/py_stub_test.pyi
- tests/py_stub_test.pyi.ref
- tests/test_typing.cpp
- tests/test_typing_ext.pyi.ref
Correct `stubgen`'s handling of nested types (e.g. a class defined inside another class).
Previously, `stubgen` generated `import` statements in the .pyi file which includes the outer type.
I fix this by testing that the module name in the generated `import` is a module by using `importlib.util.find_spec`. This is the approach [recommended by the python docs](https://docs.python.org/3/library/importlib.html#checking-if-a-module-can-be-imported): "If you need to find out if a module can be imported without actually doing the import, then you should use `importlib.util.find_spec()`."
If `stubgen` is not able to access the referenced module, the new functionality does have a graceful fall-back behavior: if none of the possible partitions of module_name and class_name result in a successful …
> Handle nested class names in stubgen

- CMakeLists.txt
find_package() is an abstraction to be used to localize a package. When building this project, the same can be achieved by just including the  `cmake/nanobind-config.cmake` file directly.
Especially the current implementation breaks in cases of using CMake dependency providers, where the dependency provider executes an `add_subdirectory` call. In this specific case the find_package leads to an infinite recursion of `find_package(nanobind)` calls.
> [cmake] include nanobind-config.cmake instead of calling find_package()

- docs/api_bazel.rst
- docs/bazel.rst
- docs/index.rst
This is designed to be a better-exposed (re: SEO) doc on how to use nanobind with Bazel, aimed at people who would like to get started with nanobind but do not want to search around reading outside documentation.
Contains sections on declaring the dependency, importing nanobind-bazel's APIs, how to use it in BUILD files, and lastly how to build extensions with Bazel.
Mentions a few noteworthy special points of information, such as constraints on the Bazel version, overriding versions with bzlmod APIs, etc.
-------------------------
This is a first draft, I still need to finish the sections on the APIs and the extension builds themselves.
Happy for comments - especially regarding depth, style, and flow. Ideally (in my opinion), the user should be able to get started by creating (at …
> Add a document explaining nanobind extension building using Bazel

- src/stubgen.py
Per https://docs.python.org/3/library/importlib.html#importlib.util.find_spec, find_spec() can throw ValueError if `__spec__` isn't set.
> Fix stubgen crash when module doesn't set __spec__

- MANIFEST.in
This is missing. Mostly generated automatically by running `pipx run check-manifest -c`, then minor touchup to make `pipx run check-manifest` pass. (I used embarrassingly used check-manifest instead of check-sdist, which is my tool that works with all backends, due to the fact it can generate a MANIFEST.in due to it's setuptools integration and I'm lazy. Don't tell anyone ;) ).
This fixes `pipx run build`, and building SDists and wheels from SDists in general.
This makes the code saved in #618 even bigger. :D
> fix: add MANIFEST.in for SDist generation

- tests/test_ndarray.py
The ndarray test `test37_noninteger_stride` uses numpy to create an array with padding between rows and then uses numpy `view()`  to convert to a complex dtype.   This capability was added in numpy 1.23.  Previously, for this conversion to work, the entire array had to be C-contiguous.
This commit fixes issue #653.
> Skip ndarray noninteger stride test for numpy<1.23.

- include/nanobind/nb_cast.h
- tests/test_functions.py
Fixes #657
Stores the size from `PyUnicode_AsUTF8AndSize()` and checks it in `can_cast<char>`.
I stored the size rather than a boolean is-length-equal-one flag, because the total struct size is the same anyway, and if we'd want to convert 2-byte UTF8 characters (U+0080 - U+00FF) to C++ chars (128-255) in the future, we'll need to check if size==2.
> type_caster<char>: allow conversion of "\0" to C++ char

- docs/api_core.rst
- include/nanobind/nb_cast.h
- src/stubgen.py
Also small stubgen fix. Need to use != operator for string comparison
> nb_cast: Add support for `parent` arg to allow for `reference_internal` rv policy

- docs/api_bazel.rst
- docs/bazel.rst
Includes stubgen with the `nanobind_stubgen()` macro, shared libraries with `nanobind_shared_library()`, and contains a small prose section on how to declare (and run) stubgen targets alongside nanobind extensions in Bazel.
Also, update all mentions of a BCR version number to v2.1.0 (current latest) to increase adoption of the latest rule version.
-------------------------------
Hi Wenzel, this is the documentation on additions made in nanobind-bazel v2.1.0, which I released to the BCR two weeks ago. Sorry for the delay, I've been in a bit of a productivity hole lately. Happy to hear your thoughts!
> Update documentation with new nanobind-bazel v2.1.0 functionality

- include/nanobind/nb_cast.h
- include/nanobind/stl/detail/nb_optional.h
- include/nanobind/stl/optional.h
- include/nanobind/stl/variant.h
Add `optional_caster<>` that works like in pybind11.
It can be used for type casting optional types other than std::optional:
boost::optional, absl::optional, nonstd::optional, llvm::Optional, etc.
I guess these types are mostly obsolete in C++17, but there still might be a reason to use other such types. In one project I use a custom OptionalInt that has 4 bytes instead of 8 (at the cost of not using INT_MIN).
> generalize type_caster<std::optional<T>>

- src/nb_internals.h
- src/nb_type.cpp
[According to the docs](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_new), the signature of `tp_new` should be: `PyObject* tp_new(PyTypeObject *subtype, PyObject *args, PyObject *kwds)`
We don't care about the arguments, but [according to the C standard clause 6.3.2.3.8](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf#page=60) this is undefined behavior:
> A pointer to a function of one type may be converted to a pointer to a
> function of another type and back again; the result shall compare equal to
> the original pointer. If a converted pointer is used to call a function whose
> type is not compatible with the pointed-to type, the behavior is undefined.
In normal platforms the behavior is to work as expected, but in WebAssembly, this crashes.
Fixes …
> Fix the signature of tp_new

- pyproject.toml
This minimum can now be single-sourced.
> chore: use scikit-build-core 0.10 and auto minimum

- src/buffer.h
`vsnprintf` is defined in `stdio.h`:
https://github.com/bminor/glibc/blob/734e7f91e752f44984fe42c2384c23a0290b6e56/libio/stdio.h#L389
All the examples include both `stdio.h` and `stdarg.h` when using `vsnprintf`. For whatever reason, on the emscripten target there is an error due to missing `vsnprintf` but on other targets there is no error.
> Include stdio.h for vsnprintf in buffer.h

- docs/api_core.rst
- include/nanobind/nb_lib.h
- include/nanobind/nb_misc.h
- src/common.cpp
Can be useful to check the state of these internal nanobind properties if for instance you only want to temporarily disable the warnings in your project and then restore the original state.
> Add leak/implicit_cast warnings getters

- docs/meson.rst
Couple things that I missed in the original PR
> Add missing robin-map installation doc for meson

- cmake/darwin-ld-cpython.sym
- docs/changelog.rst
- docs/meson.rst
- include/nanobind/nb_class.h
- src/nb_enum.cpp
- src/nb_func.cpp
- src/nb_internals.cpp
- src/nb_type.cpp
- tests/test_classes.py
nanobind has always used [PEP 590 vector calls](https://www.python.org/dev/peps/pep-0590) to efficiently dispatch calls to function and method bindings, but it lacked the ability to do so for instance constructors (e.g., ``MyType(arg1, arg2, ...)``).
Version 2.2.0 adds this missing part, which accelerates object construction by up to a factor of 2×. The difference is especially pronounced when passing keyword arguments to constructors. Note that this feature is only supported on Python 3.9+ and when building non-stable ABI extensions. If CPython PR [#123332](https://github.com/python/cpython/pull/123332) is accepted, this fast path might also become available in the stable ABI on Python 3.14+.
> Up to 2x faster instance construction using type vector calls

- docs/api_bazel.rst
- docs/bazel.rst
This is a hack since there is no Bazel domain provider available on PyPI, but it does seem to work since Starlark is a true subset of Python, and we do not have any classes or module structure to take care of.
Solves the unlucky collision of `nanobind_extension` between the CMake and Bazel docs that previously broke cross-referencing.
----------------------------
My Sphinx build logs on this branch no longer show a collision:
```
~/Workspaces/c++/nanobind move-bazel-apis-to-py-domain*
.venv ➜ sphinx-build docs docbuild -a
Running Sphinx v6.1.3
loading pickled environment... done
building [mo]: all of 0 po files
writing output...
building [html]: all source files
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] bazel
looking for now-outdated files... none found …
```
> Move Bazel API defs into Python domain

- cmake/darwin-ld-cpython.sym
- docs/changelog.rst
- include/nanobind/nb_class.h
- src/nb_internals.cpp
- src/nb_internals.h
- src/nb_type.cpp
Commit 7225e070 introduced the ability to construct types using vector calls, which can significantly improve performance. Unfortunately, the original implementation did not work in the limited API / stable ABI since it does not expose the ``tp_vectorcall`` member of ``PyTypeObject``. This commit fixes the issue by installing the vector call capability one level higher up at the metaclass level.
> Vector calls for type objects (now even in the limited API!)

- src/nb_type.cpp
- tests/test_typing.cpp
- tests/test_typing_ext.pyi.ref
I found that a compilation error occurs when the [new parameter syntax for generics](https://docs.python.org/3.12/reference/compound_stmts.html#type-params) is used as a signature. 
This fix adds the searching for `[` to the `extract_name` function.
> Fix extraction of class name with new parameter syntax

- src/nb_type.cpp
When compiling with HardwareAddressSanitizer (https://clang.llvm.org/docs/HardwareAssistedAddressSanitizerDesign.html), the top byte of pointers are tagged, hence subtracting two pointers may overflow. Overflow is undefined behavior for signed integers, resulting in errors such as:
```
third_party/nanobind/src/nb_type.cpp:123:50: runtime error: signed integer overflow: -6701078944169102656 - 9079534012674239392 cannot be represented in type 'intptr_t' (aka 'long')
```
This patch fixes the issue by using unsigned integers, for which overflow is well-defined.
> Avoid undefined behavior when subtracting tagged pointers

- tests/CMakeLists.txt
Fix the dependency between py_stub stubgen invocation and `py_stub_test.py` source file when building out of source. Previously, the dependency would be on the original file in the source directory rather than the one copied to build directory, which could lead to stubgen being invoked prior to it being copied and therefore failing to import it.
> Fix py_stub_test dependency in out-of-source builds

- .github/workflows/ci.yml
They are prone to failing when the code is changing and they happen to be available on the ubuntu-20.04 worker.
Clang 7 and 8 are currently commented out because they fail (#713).
> CI: test old GCC and Clang compilers

- .github/workflows/ci.yml
- docs/index.rst
- include/nanobind/nb_tuple.h
> Revive Clang 8 support

- docs/api_core.rst
- include/nanobind/nb_attr.h
- include/nanobind/nb_call.h
- include/nanobind/nb_cast.h
- include/nanobind/nb_func.h
- src/nb_func.cpp
An attempt at the static locking determination that I suggested in https://github.com/wjakob/nanobind/pull/695#discussion_r1752419034. Note this PR is against the free-threaded branch.
Behavior differences from the free-threaded branch without this change:
* it is no longer possible to do `nb::arg().lock(false)` or `.lock(runtime_determined_value)`; this could be re-added by restoring `cast_flags::lock` and checking the `arg_flags` at runtime, but I didn't think it was worth the complexity
* we no longer prohibit locking self in `__init__`; changing this would also require restoring `cast_flags::lock`, and it's not clear what benefit it would have (sure the lock is somewhat superfluous but do we really care?)
> Decide whether to lock function arguments at compile time

- src/stubgen.py
Fix the import problem in the stub file for old Python versions as `TypeAlias` has been available since 3.10.
> Fix importing `TypeAlias` in stubgen

- src/nb_type.cpp
Hi @wjakob in this PR I added `lock_shard guard(shard);` which may be missed in your free-threading support PR to `keep_alive` methods as I saw everywhere this pattern.
I also have a TSAN report talking about this place when running an extension with class with `nb::is_weak_referenceable`.
```
WARNING: ThreadSanitizer: data race (pid=213447)
Read of size 8 at 0x7b8c000011d0 by thread T1:
#0 tsl::rh::power_of_two_growth_policy<2ul>::bucket_for_hash(unsigned long) const /usr/local/lib/python3.13t/dist-packages/nanobind/ext/robin_map/include/tsl/robin_growth_policy.h:125 (wrlru_cache_ext.cpython-313t-x86_64-linux-gnu.so+0x45dda)
#1 tsl::detail_robin_hash::robin_hash<std::pair<void*, void*>, tsl::robin_map<void*, void*, nanobind::detail::ptr_hash, std::equal_to<void*>, …
```
> Added lock_shard guard to keep_alive

- src/nb_func.cpp
- tests/test_functions.cpp
- tests/test_functions.py
- tests/test_functions_ext.pyi.ref
Small fix for when a docstring is an empty string and is part of an overload chain.
> Overload chains with empty strings

- include/nanobind/ndarray.h
If a developer provides a specialization for, say, `dtype_traits<__fp16>` then this commit avoids his having also to provide a specialization for `dtype_traits<const __fp16>`.
> Add partial specialization dtype_traits<const T>.

- include/nanobind/nanobind.h
We use [Include What You Use](https://github.com/include-what-you-use/include-what-you-use) to manage `#include`s across a large codebase. IWYU automatically adds and removes `#include` statements in each source file to match what symbols are being used in that file. By default it tries to directly include internal nanobind headers when it detects symbols from those files.
This PR adds [`export` pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export) to tell IWYU basically the same thing as the comment on line 38 tells humans: that `nanobind.h` itself exports all of the internal symbols, and that the transitive headers should not be directly included.
We've been carrying this patch for a while and it's been working great …
> Add IWYU export pragmas to protect internal headers

- docs/api_core.rst
Looks like the word "boundary" is unintentional.
> Fix typos in Core API docs on error management.

- include/nanobind/stl/detail/nb_set.h
- tests/test_stl.py
`obj_iter` throws `python_error` on failure, but type casters aren't allowed to throw! If you try to from-Python cast an object of a non-iterable type, Python will abort from the unhandled exception coming from a `noexcept` function
It looks like the intention here is to handle failure manually (a NULL return from the CPython call), so I did just that
> Fix unhandled exception in set_caster

- docs/api_bazel.rst
- docs/bazel.rst
The code comment above the bzlmod usage was updated to reflect the change back to match nanobind SemVer exactly, starting from v2.2.0.
------------------
Hi Wenzel, this is the nanobind-bazel release for free-threading. I included a small cosmetic update of the Bazel doc, since I decided to make the change of following nanobind SemVer exactly with the newest release. More details can be found on the [release page](https://github.com/nicholasjng/nanobind-bazel/releases/tag/v2.2.0).
> Update nanobind-bazel version in Bazel document

- docs/changelog.rst
- include/nanobind/stl/variant.h
- tests/test_stl.cpp
- tests/test_stl.py
- tests/test_stl_ext.pyi.ref
When converting a Python object that wraps a `T` to a `std::variant<U,T>`, where `U` is implicitly convertible from `T`, the variant caster will cast to the `U` (even though the Python object is definitely a `T`)
The included test case demonstrates the issue. pybind11 does two pass conversion in this case. One can work around the issue by using `noconvert()` on the argument. But it seems that it would be a friendlier default to make type conversions in a variant work as expected.
> Perform two passes in the variant caster

- docs/api_core.rst
- include/nanobind/nb_types.h
Unlike `bytes`, a `bytearray` is mutable. You are allowed to write to it, and the underlying API function returns a `char*`
> Add a non-const overload of bytearray::data

- include/nanobind/nanobind.h
nb_types.h uses `std::ptrdiff_t`, which is defined in `cstddef`.
Fixes a build failure in Google's build environment, in which this header does not get included transitively by the existing headers.
> Add <cstddef> to nanobind includes.

- docs/changelog.rst
- include/nanobind/nb_class.h
- src/nb_func.cpp
- src/nb_type.cpp
- tests/test_classes.cpp
- tests/test_classes.py
- tests/test_classes_ext.pyi.ref
Fixes #786. We now consider whether it's possible to invoke the overload with no arguments, rather than just whether it is declared with no parameters; the difference is relevant in the presence of `nb::args`/`nb::kwargs` and default values. The previous logic didn't work anyway - it checked whether there was an overload with zero args, but (a) this couldn't distinguish the auto-added wrapper overload from a user-specified one and (b) neither would have zero args, because new always takes at least the type arg.
> Fix handling of overloaded __new__ that takes no arguments

- include/nanobind/eigen/dense.h
- include/nanobind/ndarray.h
- tests/test_eigen.cpp
- tests/test_eigen.py
Since https://github.com/wjakob/nanobind/commit/577942c8a13c931320db89c99d35778fc99be3d6 / https://github.com/wjakob/nanobind/pull/526, `type_caster<ndarray>::from_python` accepts None as argument, yielding an invalid ndarray. It does so independently of the cast-flags. This is fine, if the caster is called by the function dispatch mechanism, which handles cast_flags::accepts_none beforehand.
However, `type_caster<Eigen::Matrix/Array>` and `type_caster<Eigen::Map>` use `type_caster<ndarray>` as a local caster. Since these Eigen types are no wrappers, their type casters must not accept None. Part of this PR is that the local caster considers cast_flags::accepts_none, and the outer casters enforce the absence of this flag.
My use case is to avoid a read access violation when casting None …
> type_caster<ndarray>: accept None only if flags say so

- docs/changelog.rst
- include/nanobind/operators.h
- tests/test_classes.py
The idiomatic return type for `T::operator+=` in C++ is `T&`, because the idiomatic return value is `*this`. When binding `nb::self += nb::self`, or any other augmented-assignment operator, for a class that follows this convention, nanobind currently applies `rv_policy::automatic` to the `T&` return value and makes a copy of the referenced `T`. I think this is counter to users' expectations: a C++ type that defines these augmented assignment operators is mutable, so it should behave like mutable objects do in Python, and let `+=` preserve object identity. The problem is demonstrated by the test in this PR, which fails on current master.
Fix this issue by defaulting to `rv_policy::move` for the return value of augmented assignment operators. This will work as it does today if the operator …
> Default to rv_policy::move when binding in-place operators

- docs/changelog.rst
- src/nb_type.cpp
- tests/test_classes.cpp
- tests/test_classes.py
- tests/test_classes_ext.pyi.ref
See
https://github.com/pybind/pybind11/commit/e0e2ea33788e29ff5efca5842e92c6b179ca9378 for the analogous change to pybind11.
> Support overriding static properties defined via def_prop_ro_static.

- docs/api_core.rst
- docs/changelog.rst
- include/nanobind/nb_misc.h
- tests/test_functions.cpp
- tests/test_functions.py
The current `isinstance<T>(inst)` tests if a Python object is an instance of a bound C++ class. This new overload tests if a Python object is an instance of a Python class. I have needed this helper in several nanobind-using codebases, and the same API exists in pybind11.
> Add an API isinstance(inst, cls) that mirrors the Python isinstance.

- docs/faq.rst
Hi,
I am the creator of [litgen](https://pthom.github.io/litgen), an automatic binding generator for pybind11 which generates documented C++ binding code together with python stubs.
Recently it was updated to also support nanobind (with help from @davidlatwe)
This PR proposes to mention litgen in the nanobind documentation, in two parts:
- 9454073: In the building.rst page, I added a section called "Generating binding code automatically," similar to what’s in the pybind11 documentation, to explain litgen’s role in generating documented, discoverable bindings for both pybind11 and nanobind.
- 63f3386: In the porting.rst page, I included a link to the litgen documentation, highlighting examples that compare pybind11 and nanobind binding code side by side. This should be helpful for users …
> Doc: add info about litgen binding generator

- src/nb_internals.h
- src/nb_ndarray.cpp
- src/nb_static_property.cpp
- src/nb_type.cpp
In a couple of places in nanobind we see this idiom:
```
nb_internals *internals_ = internals;
PyTypeObject *tp = internals_->nb_ndarray;
if (NB_UNLIKELY(!tp)) {
lock_internals guard(internals_);
tp = internals_->nb_ndarray;
if (tp)
return tp;
// ... build tp
internals_->nb_ndarray = tp;
}
```
This is the classic double-checked locking idiom, which on architectures that don't have total store ordering is racy (e.g. ARM, not x86). To use this pattern correctly, we need to use an atomic acquire load for the read outside the lock, and to use an atomic store release for the store inside the lock. These add the necessary fences to ensure that, for example, the contents of `tp` do not appear populated to the reader before the writer has stored them to memory.
This PR adds an include of …
> Use atomic reads and writes in code that uses double-checked locking.

- src/__init__.py
This is useful when building with other tools or build systems, like `setuptools` in my case.
-------------
Right now, to obtain the source path, I am using `Path(nanobind.include_dir()).with_name("src")`, but I felt that this was a worthy addition for anyone needing the sources path when building nanobind from source themselves as part of a package / wheel build by means other than scikit-build-core.
> Add `nanobind.source_dir()` API to obtain the source path

- docs/api_bazel.rst
- docs/bazel.rst
`nanobind_bazel` v2.4.0 was released on the BCR on christmas. The MODULE.bazel code example is thus updated, as is tradition, along with two more user-facing changes:
1. The minimum Bazel version was increased to Bazel 7, since we need to use a sufficiently new `rules_python` for free-threading support.
2. The `@nanobind_bazel//:free_threading` flag was removed, since it was not that useful - you still needed to give `rules_python`'s free-threading flag separately to request a free-threaded toolchain, and supplying it did not even guarantee a free-threading build. Now, we just use `rules_python`'s free-threading flag value directly instead.
> Update nanobind-bazel docs with latest developments

- include/nanobind/make_iterator.h
- tests/common.py
- tests/test_make_iterator.py
- tests/test_thread.py
The `State` class used by make_iterator is constructed lazily, but without locking it is possible for the caller to crash when the class type is only partially constructed. This PR adds an ft_mutex around the binding of the State type.
My initial instinct was to use an `nb_object_guard` on `scope`. Unfortunately this doesn't work; I suspect `PyEval_SaveThread()` is called during class binding and that releases the outer critical section.
> Fix crash from concurrent nb::make_iterator<> under free-threading.

- tests/test_classes.cpp
An out-of-the box build with Debian trixie (i.e., with g++ 14.2.0) gives the following warning:
```
warning: redundant move in return statement [-Wredundant-move]
508 |     m.def("test_type_object_t", [](nb::type_object_t<Struct> h) -> nb::object { return std::move(h); });
|                                                                                        ~~~~~~~~~^~~
```
Since the return expression is move-eligible, the move constructor is selected without the `std::move`.
> Remove redundant move in test

- src/nb_type.cpp
- tests/test_thread.cpp
- tests/test_thread.py
> Fix race condition involving wrapper lookup

- docs/api_core.rst
- docs/free_threaded.rst
* Bytes are not unicode
* the word "section" was missing from a sentence in the free-threading section
* replaced "the project" with "nanobind" in the same sentence,
'cause that's somewhat more clear prose to this reader
> Two small doc fixes

- docs/api_core.rst
- docs/changelog.rst
- include/nanobind/nb_class.h
This has two purposes:
* I'm planning to contribute some `class_` extensions (for pickling and buffer protocol support) that I would like to be able to put in their own headers so they don't slow down compilation for those that don't use them. This PR allows `class_::def()` to perform an operation that was not foreseen by the code inside `class_`.
* I've found it quite ergonomically useful (and am carrying a local patch) to be able to add customizations by chaining `.def(my_thing())` to a class binding, rather than the existing supported alternative of giving the binding a name and calling a helper function on it (`auto someCls = nb::class_<...>(...); my_thing(someCls);`).
Previously `class_filler`, renamed to `def_visitor` per feedback.
> Introduce def_visitor abstraction for objects that provide custom binding logic when passed to def()

- docs/free_threaded.rst
- src/nb_type.cpp
- tests/test_thread.cpp
- tests/test_thread.py
This commit addresses an issue arising when multiple threads want to access the Python object associated with the same C++ instance, which does not exist yet and therefore must be created. @vfdev-5 reported that TSAN detects a race condition in code that uses this pattern, caused by concurrent unprotected reads/writes of internal ``nb_inst`` fields.
To fix this issue, we split instance creation and registration into a two-step process. The registration is only done when the object is fully constructed.
> Fix race condition in free-threaded Python (fixes issue #867)

- src/nb_internals.cpp
Most terminals don't have 10k line s of scrollback buffer ...
> Don't print too many "leaked instance" messages.

- cmake/nanobind-config.cmake
- docs/api_cmake.rst
With this change compile commands generated by cmake for targets consuming nanobind use `-isystem` instead of `-I` for defining nanobind's header locations, which makes modern analysis tools (e.g. clang-analyzer) ignore them.
> Introducing option NB_SUPPRESS_WARNINGS to nanobind_add_module

- src/nb_type.cpp
See https://github.com/python/cpython/issues/129675#issuecomment-2638095421
`tp_basicsize` needs to be a multiple of the alignment of `PyObject`, which is in effect pointer aligned.
This fixes a SIGBUS alignment crash found when testing free-threaded nanobind-using code on aarch64.
> Fix underalignment of nanobind-bound classes.

- src/nb_ndarray.cpp
Using `rv_policy::copy` for torch tensors is currently broken. Produces the following error:
```
RuntimeError: nanobind::detail::ndarray_export(): copy failed: AttributeError: 'Tensor' object has no attribute 'copy'
```
The error message is correct, torch tensors don't have an out-of-place `copy` attribute, they have `clone()`.
I added a simple if statement to change out the attribute name in the ndarray export function. If other frameworks have similar issues, could be expanded to a switch case or so.
> ndarray: use clone to copy return pytorch tensors

- include/nanobind/typing.h
- src/nb_ft.h
This adds `#pragma once` to the following headers:
- The public header `<nanobind/typing.h>`, which would result in an error if included twice.
- The private header `src/nb_ft.h`, which _is_ included twice by `nb_combined.cpp`, resulting in an error (at least in my environment).
(There are additional private headers that lack `#pragma once`; I'm leaving those alone here.)
> Add missing #pragma once

- docs/api_bazel.rst
- docs/bazel.rst
Bumps the version number in MODULE.bazel, and mentions the additional keyword arguments supported in `nanobind_stubgen`.
> docs: Add resources for nanobind-bazel v2.5.0 changes

- .github/workflows/ci.yml
- cmake/darwin-ld-cpython.sym
- src/common.cpp
When an attribute lookup fails, Python spends a significant chunk of CPU cycles formatting and then raising an exception.
The ``nb::getattr(object, key, default)`` API provides a fallback ``default`` value in the case of an error. The expense of raising an exception is therefore not wanted here.
This commit avoids this exception by
- using the new ``PyObject_GetOptionalAttr()`` function on Python 3.13+
- using an internal ``_PyObject_LookupAttr()`` API before Python 3.13.
- on the 3.12 stable API, using ``PyObject_HasAttr()`` before doing the lookup.
> Faster attribute lookup

- include/nanobind/stl/chrono.h
The type casters in `stl/chrono.h` accept various types in their
`from_python` calls, but they currently just use a name for their
output type.
This uses `io_name` to differentiate, adding the various acceptable
types that the casters permit at runtime
This also includes type stub testing for the `test_chrono_ext` module. The
first commit in this PR contains the stubs only.
> Add input types to chrono type casters

- cmake/nanobind-config.cmake
This is an empty string when it's not building for the Stable ABI.
I chose to check if it's defined and check if it's empty in two steps, though if you'd prefer, the empty check also is False if it's not defined. The form I used is slightly clearer, and might work a little better if someone passes `--warn-uninitialized` (maybe the second one passes that too, not sure).
Fix for regression in #978.
> fix(cmake): Handle empty SKBUILD_SABI_VERSION

- include/nanobind/stl/unique_ptr.h
- tests/test_holders.cpp
This uses the same technique that the `shared_ptr` type caster does. The updated test previously failed because of an invalid conversion from `const void*` to `void*`
> Support casts of const-qualified unique_ptrs

- include/nanobind/eigen/sparse.h
- tests/test_eigen.py
Hi,
I've just encountered an issue when the user passes a scipy sparse matrix with unsorted inner indices to Eigen.
This issue manifests in two ways:
- an `eigen_assert()` is triggered when compiling in Debug,
- or you can get incorrect values in your converted sparse matrix.
It seems until [relatively recently](https://gitlab.com/libeigen/eigen/-/merge_requests/1099) it was not explicitly stated that `Eigen::Map<SparseMatrix>` objects expect the inner indices to be sorted. This issue really pops up when you try to evaluate the map into a plain sparse matrix object, like here:
https://github.com/wjakob/nanobind/blob/10eafbc528574a7045133e9751d00c8bd61ae0da/include/nanobind/eigen/sparse.h#L89
Eigen's master branch has a nice `a.sortInnerIndices()` function and some helpers to check if the …
> Eigen: Demonstrate and fix issue with passing `scipy.sparse` matrices with unsorted indices

- src/stubgen.py
- tests/CMakeLists.txt
- tests/conftest.py
- tests/test_jax.cpp
- tests/test_jax_ext.pyi.ref
- tests/test_ndarray.cpp
- tests/test_ndarray.py
- tests/test_ndarray_ext.pyi.ref
- tests/test_stubs.py
- tests/test_tensorflow.cpp
- tests/test_tensorflow_ext.pyi.ref
This PR is stacked on top and, therefor, contains the commits of #939.
This PR changes the logic of `is_valid_module` used in `simplify_types`. That function uses `importlib.util.find_spec` and previously tested the return value for `is None`. However, (1) if the spec is actually `None`, then the function doesn't return `None` but raises `ValueError`, so that test never succeeded and (2) if a module with a `None` spec was found, we have still found a module, so `is_valid_module` should actually return `True` instead of `False`.
> stubgen: Fix the detection of modules without spec.

- cmake/nanobind-config.cmake
Pull request for #994 as requested. Not disabling this could lead to build failures in projects where clang-tidy is globally enabled if one included the project as a submodule.
> Disable clang-tidy on nanobind library

- include/nanobind/nb_types.h
My understanding is that #500 concluded that it is fine to use `Py_XINCREF` and `Py_XDECREF` with `Py_LIMITED_API`.
If so, it seems preferable from a performance point of view.
Please review this PR carefully and correct me if I'm wrong.   I'm not a Python expert.
> Use Py_XINCREF,Py_XDECREF also with Py_LIMITED_API

- docs/refleaks.rst
- tests/test_classes.cpp
- tests/test_stl.cpp
* In wrapper_tp_traverse in test_classes.cpp, make sure to visit the type.
* In both the tp_traverse docs and tests, do not visit the contents of the C++ object if the instance is not ready. A nanobind object is tracked for GC at the end of PyType_GenericAlloc, but that is before the constructor is called. If a GC occurs between the two, we may end up trying to traverse an unconstructed C++ object. We found this to happen in practice in JAX.
* Update the Wrapper type in the docs to use a std::shared_ptr<Wrapper>. It makes no sense to use nb::find if the type is an nb::object.
> Fix bugs in tp_traverse examples and documentation.

- docs/changelog.rst
- docs/eigen.rst
- include/nanobind/eigen/sparse.h
- tests/test_eigen.cpp
- tests/test_eigen.py
This PR adds support for taking and returning sparse matrix maps (including complex-valued ones). As with passing dense maps, the type caster is extra picky and only accepts the zero-copy case. There is now also some extra documentation that explains caveats about returning maps in general.
> Support `Eigen::Map<Eigen::SparseMatrix>` [updated]

- src/version.py
This is a continuation of #1010, which is non-reopenable because I force pushed to avoid a merge commit.
FYI, my motivation is improved Meson support.  Meson's [WrapDB](https://mesonbuild.com/Using-the-WrapDB.html) adds an overlay (or patch) on top of the nanobind source code to provide the file [meson.build](https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/nanobind/meson.build).  This file currently contains the nanobind version number:
```
project( 'nanobind',   'cpp',
version: '2.4.0',
meson_version: '>=0.53.0',
license: 'BSD-3-Clause',
)
```
After the next release of nanobind (and there's no hurry as far as I'm concerned) and with this PR, this can become
```
project( 'nanobind',   'cpp',
version: run_command('src/version.py', check: true).stdout().strip(), …
```
> Add python script src/version.py

- docs/api_bazel.rst
- docs/bazel.rst
In particular, notes the experimental nature of the underlying `cc_static_library` rule. The `"cp314"` value for the stable ABI flag was added to the list of legal input values.
Also removes linebreaks in some links to the Bazel docs, which were broken at least in VSCode.
> docs: Add doc on new `nanobind_static_library` macro, cp314 SABI option

- src/stubgen.py
See more details in https://github.com/wjakob/nanobind/issues/1023
> stubgen.py: enhance 'param_str' method to handle default value that is a nanobind object

- docs/meson.rst
@WillAyd, I changed the C++ source code suffix to `cpp` simply to be consistent with the rest of the nanobind docs.  I'm not trying to impose my convention on others.  :)
Debian 12 (bookworm, the current stable version) includes meson 1.0.1, which is sufficient for building non-stable-ABI python extensions, but using the keyword argument `limited_api` requires meson 1.3.0.   This is why I included `meson.build` in full for building against the python stable ABI.
I'll leave this PR as a draft until https://github.com/mesonbuild/wrapdb/pull/2104 is merged in case additional changes are advisable.
Regards,
Paul
> docs: Updates for building an extension with meson

- docs/api_core.rst
- include/nanobind/nb_types.h
Description:
- Added empty() methdo to tuple/list/dict/setfor a certain level of parity with pybind11
- pybind11 has size and empty methods on sequence, but nanobind seems not to expose these methods   
Context: when ported pybind11 code to nanobind was expecting to have the same method in nanobind.
Related to https://github.com/wjakob/nanobind/discussions/1026#discussioncomment-13200460
cc @wjakob
> Added empty() method to tuple/list/dict/set

- include/nanobind/nb_defs.h
Otherwise GCC complains:
```
include/nanobind/nb_defs.h:205:80: warning: backslash-newline at end of file
205 | #define NB_MODULE(name, variable)                                              \
```
> Fix backslash at the end of file

- include/nanobind/nb_class.h
If compiling with clang++-19 and `-Wpedantic`, the following warning is seen:
```
warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
```
Of course, this is easily silenced by adding the flag `-Wno-nested-anon-types`.
Alternatively, this PR avoids the warning by giving names to the two struct types.
Please feel free to merge or reject as you think best.
Regards,
Paul
> Consider adding struct names implicit_t and enum_tbl_t

- docs/api_core.rst
- docs/exchanging.rst
- src/hash.h
Also terminates the constructor doc with a dot as per the style in the other docs, and removes a mention of MurmurHash from `src/hash.h`, which has been removed since that note was written.
> docs: Add frozenset to available wrapper list

- cmake/nanobind-config.cmake
The CMake doc https://cmake.org/cmake/help/latest/command/if.html says
> Per legacy, the `else()` and `endif()` commands admit an optional `<condition>` argument.
> If used, it must be a verbatim repeat of the argument of the opening `if` command.
I think the logic here makes sense:
- If Python is free-threaded, do not build an extension with the stable ABI (i.e., ignore STABLE_ABI)
- If Python is not free-threaded, do not build a free-threaded extension (i.e., ignore FREE_THREADED)
This makes it OK for an extension's CMakeLists.txt to specify both STABLE_ABI and FREE_THREADED.
The choice of what to build is based on what Python is found (e.g., by setting Python_ROOT_DIR).
> Remove argument from Cmake else() command

- include/nanobind/nb_types.h
The Intel `icpx` 2025.2.0 compiler, which is based on clang, warns that identifier '_s' preceded by whitespace in a literal operator declaration is deprecated.
That seems to be correct.  https://en.cppreference.com/w/cpp/language/user_literal.html documents
> `user-defined-string-literal`  the character sequence "" followed, without a space, by the character sequence that becomes the `ud-suffix`
Note that nanobind's definition of `operator""_a` in `nb_attr.h` does not have whitespace, so this PR is consistent.
> Remove space from user defined string literal

- docs/meson.rst
- docs/typing.rst
Also, update the links in `typing.rst` since the old link now simply refers to the two newly added links.
@WillAyd, please review at your convenience.
Thanks,
Paul
> docs: Add stubgen instructions using Meson

- cmake/nanobind-config.cmake
- src/nb_internals.cpp
When `NB_COMPACT_ASSERTIONS` is defined and `fail_unspecified()` is called, this changes the printed output from:
```
Critical nanobind error: nanobind: encountered an unrecoverable error condition. Recompile using the 'Debug' or 'RelWithDebInfo' modes to obtain further information about this problem.
```
to
```
Critical nanobind error: encountered an unrecoverable error condition. Recompile using the 'Debug' mode to obtain further information about this problem.
```
> Improve fail_unspecified()'s default error message

- docs/api_core.rst
- include/nanobind/nb_tuple.h
- tests/test_functions.cpp
- tests/test_functions.py
Given `nb::detail::tuple<int, int> tpl = {3, 17};` neither `auto [aa, bb] = tpl;` nor `auto t2 = tpl;` currently compiles.
To fix this, this PR conditionally enables the templated constructor so it is less greedy.
Also, this adds a sentence to slice's compute function to describe how to obtain the elements of a `detail::tuple`.
> Enable copying of detail::tuple objects

- docs/api_core.rst
The `operator[]` **is** listed below in the docs for `tuple` and `list`.
> docs: minor fix regarding operator[]

- src/nb_enum.cpp
Since they are now available, use them instead of the tp.attr() assignment strategy, which is harder to read. No functional changes intended.
Follow-up of #1119.
> Use in-place operators in enum mask calculations

- src/stubgen.py
Use a maximally permissive type instead.
> Don't crash if inspect.signature() fails on a function during stubgen.

- src/nb_internals.cpp
There was a small typo in the original changes in #883 which caused function leak reports to be printed unconditionally
> Fix shortened leaked functions reporting

- include/nanobind/nb_attr.h
- include/nanobind/nb_func.h
- include/nanobind/nb_lib.h
- include/nanobind/nb_types.h
- src/nb_func.cpp
This PR avoids using a zero-length array by adding a base class `func_data_prelim_base` and specializing `func_data_prelim<0>` not to have an `args` member.
Using MSVC, we no longer have member `arg_data args[1]` when `Size == 0`.
Using g++ or clang++, the following hold true on Linux with or without this PR:
```
static_assert(sizeof(nb::detail::func_data_prelim<0>) == 88);
static_assert(sizeof(nb::detail::func_data_prelim<1>) == 128);
static_assert(sizeof(nb::detail::func_data_prelim<2>) == 168);
```
> Avoid zero-length arrays

- docs/bazel.rst
Same as always, Bazel central registry PR is https://github.com/bazelbuild/bazel-central-registry/pull/5850.
> Bump nanobind_bazel version to v2.9.2

- src/version.py
This relieves the need to update the nanobind_bazel documentation entry by hand after each stable release. Technically, there is a brief period(until the subsequent BCR release of nanobind_bazel) during which the documentation contains non-working MODULE.bazel code.
However, this risk is probably acceptable, since I release nanobind_bazel typically in short order after each nanobind release, and the command to override nanobind_bazel from GitHub can be found directly below.
No other changes intended - specifically, no print statements or other logging were added to preserve stdout behavior expected by Meson.
---------------------
As per our latest discussion.
The new script leaves docs unchanged on dev version bumps (i.e. `python src/version.py -w X.Y.Z-dev1`, and updates on stable …
> Extend `src/version.py` script to `nanobind_bazel` docs
