wjakob/nanobind

- include/nanobind/stl/function.h
- src/internals.h
Just fixes the noexcept annoyance.
> Fix minor noexcept issue

- include/nanobind/nb_class.h
- pyproject.toml
- setup.py
- src/nb_func.cpp
- tests/test_classes.py
- tests/test_enum.py
- tests/test_functions.py
- tests/test_holders.py
This makes a few minor fixes detected and while looking at the code and via
some automated tooling. If this looks good, I'll probably have a few followups,
ending with a pre-commit file that will help keep this clean and tidy. :)
- docs: fix spelling
- chore: clean up some minor stylistic issues
- fix: always include build-backend when using pyproject.toml
> chore: some minor cleanups

- tests/test_classes.cpp
- tests/test_holders.cpp
[clang tidy modernization](https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html)
> use make_unique

- include/nanobind/operators.h
- include/nanobind/stl/shared_ptr.h
- include/nanobind/stl/tuple.h
- include/nanobind/stl/unique_ptr.h
- include/nanobind/tensor.h
Hey guys,
thank you for the great project! I noticed that some header files are missing include guards, this PR adds them to all non-nb_* include files.
Cheers, Moritz
> add pragma once guards

- src/nb_enum.cpp
- src/nb_type.cpp
- tests/test_enum.py
Add nb_enum_hash using Py_tp_hash, as suggested in https://github.com/wjakob/nanobind/discussions/105 .
> Support hashing enumeration values

- include/nanobind/nb_types.h
> fast_iterator satisfies std::forward_iterator concept

- docs/ndarray.rst
Fixes https://github.com/wjakob/nanobind/issues/154
> [docs] fixing typo

- CMakeLists.txt
Slows down the config looking for and testing a C compiler.
> fix: a C compiler is not required

- docs/changelog.rst
- docs/packaging.rst
- src/nb_internals.h
- tests/CMakeLists.txt
- tests/test_classes.py
- tests/test_stl.cpp
- tests/test_stl.py
This commit makes a few small changes to enable compilation on 32 bit processors. I've only tested i686 on Linux so far, but that works without problems.
> 32 bit support

- include/nanobind/stl/detail/nb_list.h
- tests/test_stl.cpp
- tests/test_stl.py
See https://stackoverflow.com/a/34079497/9759769
> Update nb_list.h to allow for std::vector<bool>, see #255

- src/nb_func.cpp
> Fix docstrings becoming invalid due to scope

- cmake/collect-symbols-pypy.py
- cmake/collect-symbols.py
- src/__main__.py
- src/nb_func.cpp
- src/stubgen.py
- tests/test_functions.py
See #437
Reopening as I accidentally closed it.
> Change __nb_signature__ format for functions + Improve typing in python scripts

- docs/ndarray.rst
> docs: Update ndarray.rst

- src/stubgen.py
- tests/common.py
- tests/py_stub_test.pyi.ref
- tests/test_classes_ext.pyi.ref
- tests/test_enum_ext.pyi.ref
- tests/test_functions_ext.pyi.ref
- tests/test_make_iterator_ext.pyi.ref
- tests/test_ndarray_ext.pyi.ref
- tests/test_stl_ext.pyi.ref
- tests/test_typing_ext.pyi.ref
See https://github.com/wjakob/nanobind/issues/420#issuecomment-1986957935
> Sorted imports

- include/nanobind/stl/complex.h
- tests/test_stl.py
> Fix problem where `std::complex` caster always succeeded

- src/stubgen.py
Fixes https://github.com/wjakob/nanobind/issues/420#issuecomment-2023992428
> Fix possible ValueError during stubgen

- src/stubgen.py
- tests/test_enum_ext.pyi.ref
This MR addresses the comment made [here](https://github.com/wjakob/nanobind/issues/420#issuecomment-2108221414).
> Update stubgen of enums to include literal values

- docs/api_core.rst
- docs/changelog.rst
- docs/classes.rst
- include/nanobind/nb_attr.h
- include/nanobind/nb_class.h
- include/nanobind/nb_python.h
- src/nb_enum.cpp
- tests/test_enum.cpp
- tests/test_enum.py
- tests/test_enum_ext.pyi.ref
Continuation of #599, as discussed.
I'm interested in how to fix the tests - I added extra logic on which metaclass and ` __str__` method to use as per https://github.com/wjakob/nanobind/pull/599#discussion_r1689110819, but this breaks more tests than before.
> Add support for Flag enums, continued

- docs/api_core.rst
As noted by @wojdyr in https://github.com/wjakob/nanobind/discussions/816#discussioncomment-11561279 - thanks for catching!
> Fix off-by-one error in nb::call_policy documentation

- src/nb_func.cpp
Nanobind previously distinguished between a "complex" and a "simple" function dispatcher. This PR adds variants of the simple dispatcher that further specializes to 0 and 1-argument functions without overloads. One common class of functions that benefits are property getters.
The speedup is pretty small (~2%), but we will take it :-).
> Specialized function dispatchers for very simple functions

- docs/api_core.rst
- docs/changelog.rst
- include/nanobind/nb_types.h
- tests/test_functions.cpp
Easy compatibility with pybind11 code
> Add _s literals

- .github/workflows/ci.yml
- include/nanobind/nb_defs.h
- src/common.cpp
This commit switches nanobind from single to multi-phase initialization. It only updates the entry point but changes no other functionality.
> Multiphase initialization
